### ISSUE TITLE
Unworkable

### ISSUE THREAD

**Issue by Yui907** [ronith256/LocalGPT-Android#5]
![Screenshot_2024-12-19-02-02-23-050_com lucario gpt4allandroid](https://github.com/user-attachments/assets/2a415341-3a56-464c-b53c-df3c43e2cd7a)

Buggy is an understatement.
Is there a ability to use our own models?

**Comment by ronith256** [comment]
Not really, it's using gpt4j backend so models like llama won't work. This is a dead project as of now.
